name: leading-zeros
limit: 1000
memory_size: 0x1000
input_streams:
  0x80: [1]
  0x84: []
reports:
  - name: Log
    slice: all
    view: |
      {pc}:	{instruction}	{pc:label}
  - name: Result
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [31]
