name: assert reverse_string_cstr('1234567890\012345\n') == ('0987654321', '')
# and mem[0..31]: 30 39 38 37 36 35 34 33 32 31 00 31 32 33 34 35 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f
limit: 2000
memory_size: 0x1000
input_streams:
  0x80: [49, 50, 51, 52, 53, 54, 55, 56, 57, 48, 0, 49, 50, 51, 52, 53, 10]
  0x84: []
reports:
  - name: Check results
    slice: last
    filter:
      - state
    view: |
      numio[0x80]: {io:0x80:dec}
      numio[0x84]: {io:0x84:dec}
      symio[0x80]: {io:0x80:sym}
      symio[0x84]: {io:0x84:sym}
      {memory:0:31}
    assert: |
      numio[0x80]: [] >>> []
      numio[0x84]: [] >>> [48,57,56,55,54,53,52,51,50,49]
      symio[0x80]: "" >>> ""
      symio[0x84]: "" >>> "0987654321"
      mem[0..31]: 	30 39 38 37 36 35 34 33 32 31 00 31 32 33 34 35 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f

# name: assert reverse_string_cstr('hello\n') == ('olleh', '')
# # and mem[0..31]: 6f 6c 6c 65 68 00 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f 5f
# limit: 2000
# memory_size: 0x1000
# input_streams:
#   0x80: [104, 101, 108, 108, 111, 10]
#   0x84: []
# reports:
#   - name: step-by-step
#     slice: all
#     view: |
#       {D2} {D3} {A5} {SR:bin}
#       {pc}:	{instruction}	{pc:label}
#   - name: Check results
#     slice: last
#     filter:
#       - state
#     view: |
#       numio[0x80]: {io:0x80:dec}
#       numio[0x84]: {io:0x84:dec}
#       symio[0x80]: {io:0x80:sym}
#       symio[0x84]: {io:0x84:sym}
#     assert: |
#       numio[0x80]: [] >>> []
#       numio[0x84]: [] >>> [111,108,108,101,104]
#       symio[0x80]: "" >>> ""
#       symio[0x84]: "" >>> "olleh"
